### ISSUE TITLE
Wrong code version?

### ISSUE THREAD

**Issue by raymondjstone** [Duet3D/DWC-CNC#4]
Might be a silly question but when I fork this to allow me to deploy to an azure status site for testing before putting on a trea board I get what looks like the normal 3d Printer interface and NOT the CNC one

**Comment by Sindarius** [comment]
The CNC dashboard controls show up when the Duet is set to CNC mode so if you are deploying it to a testing site I imagine the object model is not populated so it won't know it is running in CNC mode.

**Comment by raymondjstone** [comment]
thank I will look to how to set that
