### ISSUE TITLE
Goto Work zero does not act in the most safe method

### ISSUE THREAD

**Issue by raymondjstone** [Duet3D/DWC-CNC#8]
In other UI's the goto work zero function will for safety raise the Z to max before moving and then after at location move the Z to the correct height, Could you adopt this method as well,

The macro run in other UI's would be like this I believe

G1 H1 Z1500 F1500 ; raise the Z to the highest position
G1 X0 Y0 F1500 ; go directly above the work zero position
G1 Z0 F1500 ; go to the work Z zero position

**Comment by zzpaulzz** [comment]
I had problems with this macro and had to revert to 
M98 Phomez.g
G1 X0 Y0 F2400 ; go directly above the work zero position
G1 Z0 F1500 ; go to the work Z zero position

**Comment by Sindarius** [comment]
The later versions of DWC-CNC calls workzero.g.  Make sure you set that macro to safely go to zero..

**Comment by zzpaulzz** [comment]
Just to be clear please.  This system file? This is what I'm using.  All good?
```
; workzero.g
; called GO TO WORK ZERO is pressed in WorkBee Control

M98 Phomez.g
G1 X0 Y0 F2400 ; go directly above the work zero position
G1 Z0 F1500 ; go to the work Z zero position 
```

**Comment by Sindarius** [comment]
This is what I personally use on my CNC. But if your workzero.g is working for you then it should be fine.

```
G91
G1 H3 Z90 F500
G90
G1 X0 Y0 F6000
G1 Z0
```
